/*
1 CREER UN NOUVEAU DOSSIER 
2 CREEZ UNE PAGE page.html
3 METTRE SUR GIT
4 CREEZ LE LIEN AVEC LE CSS 
5 CREEZ LE LIEN AVEC LE JS
6 AU CHARGEMENT DE LA PAGE : Dans la console on affiche bienvenue sur la page html
7 CREEZ UN BOUTTON DANS LA PAGE
8 LORSQU ON CLIQUE SUR LE BOUTON IL Y A UNE ALERT AFFICHANT BIENVENUE SUR LE BOUTTON
9 LORSQU ON CLIQUE SUR LE BOUTON IL Y A UNE ALERT AFFICHANT CE QUI ECRIT SUR LE BOUTON
*/